import { Flower } from '../types';

export const flowers: Flower[] = [
  // Indian Flowers
  {
    id: '1',
    name: 'Premium Red Roses',
    price: 170,
    image: 'https://cdn.mos.cms.futurecdn.net/LNmih3ug6YZufqNSHh52mD.jpg',
    description: 'Luxurious red roses perfect for expressing deep love and passion. Hand-picked for freshness. ₹170 per piece, ₹180 per kg.',
    category: 'roses',
    origin: 'India',
    color: 'red',
    occasion: ['anniversary', 'valentine', 'romantic'],
    inStock: true,
    rating: 4.9,
    reviews: 247,
    sizes: ['dozen', 'half-dozen', 'single','large quantities for occasion'],
    sameDay: false
  },
  {
    id: '2',
    name: 'Pink Rose',
    price: 175,
    image: 'https://wildroots.in/wp-content/uploads/2020/10/d888e6833966f34a7bfb193e1d8addb3.jpg',
    description: 'Soft pink roses symbolizing grace and elegance. Perfect for expressing admiration. ₹175 per piece, ₹185 per kg.',
    category: 'roses',
    origin: 'India',
    color: 'pink',
    occasion: ['birthday', 'appreciation', 'any special ocassion'],
    inStock: true,
    rating: 4.8,
    reviews: 189,
    sizes: ['dozen', 'half-dozen', 'bouquet'],
    sameDay: false
  },
  {
    id: '3',
    name: 'White Rose Purity',
    price: 180,
    image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSbpLVgrTrY_xIe6DsmIk4KTSqJblMGPGtpPQ&s',
    description: 'Pure white roses representing new beginnings and eternal love. ₹180 per piece, ₹190 per kg.',
    category: 'roses',
    origin: 'India',
    color: 'white',
    occasion: ['wedding', 'sympathy', 'new-beginning'],
    inStock: true,
    rating: 4.9,
    reviews: 156,
    sizes: ['dozen', 'arrangement', 'bridal'],
    sameDay: false
  },
  {
    id: '4',
    name: 'Golden Marigolds (Genda)',
    price: 12,
    image: 'https://m.media-amazon.com/images/I/61Jw931dBGL._UF1000,1000_QL80_.jpg',
    description: 'Vibrant golden marigolds, auspicious flowers for festivals and celebrations. ₹12 per piece, ₹120 per kg.',
    category: 'marigolds',
    origin: 'India',
    color: 'yellow',
    occasion: ['festival', 'diwali', 'decoration'],
    inStock: true,
    rating: 4.6,
    reviews: 203,
    sizes: ['garland', 'loose', 'bouquet'],
    sameDay: false
  },
  {
    id: '5',
    name: 'Orange Marigold Garland',
    price: 10,
    image: 'https://www.bigbasket.com/media/uploads/p/m/20001035-2_8-fresho-marigold-flower-orange.jpg',
    description: 'Traditional orange marigold garlands for religious ceremonies and festivals. ₹10 per piece, ₹100 per kg.',
    category: 'marigolds',
    origin: 'India',
    color: 'orange',
    occasion: ['religious', 'festival', 'puja'],
    inStock: true,
    rating: 4.7,
    reviews: 145,
    sizes: ['garland', 'small-garland', 'decoration'],
    sameDay: false
  },
  {
    id: '6',
    name: 'Fragrant Jasmine (Mogra)',
    price: 18,
    image: 'https://m.media-amazon.com/images/I/61L5P5d9kWL.jpg',
    description: 'Intensely fragrant white jasmine flowers, perfect for hair decoration and worship. ₹18 per piece, ₹180 per kg.',
    category: 'jasmine',
    origin: 'India',
    color: 'white',
    occasion: ['religious', 'hair-decoration', 'wedding'],
    inStock: true,
    rating: 4.8,
    reviews: 167,
    sizes: ['string', 'loose', 'small-bouquet'],
    sameDay: false
  },
  {
    id: '7',
    name: 'Red Hibiscus (Japa)',
    price: 15,
    image: 'https://m.media-amazon.com/images/I/71LyL+e2VtL._UF1000,1000_QL80_.jpg',
    description: 'Bright red hibiscus flowers, sacred to Hindu goddess Kali and perfect for worship. ₹15 per piece, ₹150 per kg.',
    category: 'hibiscus',
    origin: 'India',
    color: 'red',
    occasion: ['religious', 'puja', 'decoration'],
    inStock: true,
    rating: 4.5,
    reviews: 98,
    sizes: ['single', 'bunch', 'garland'],
    sameDay: false
  },
  {
    id: '8',
    name: 'Sacred Pink Lotus (Kamal)',
    price: 25,
    image: 'https://www.saharanpurnursery.in/cdn/shop/files/Pink-Lotus-Flower-Meaning_700x700.jpg?v=1718611176',
    description: 'Sacred pink lotus, India\'s national flower symbolizing purity and enlightenment. ₹25 per piece, ₹200 per kg.',
    category: 'lotus',
    origin: 'India',
    color: 'pink',
    occasion: ['religious', 'meditation', 'spiritual'],
    inStock: true,
    rating: 4.9,
    reviews: 89,
    sizes: ['single', 'pair', 'arrangement'],
    sameDay: false
  },
  {
    id: '9',
    name: 'Bright Sunflowers (Surajmukhi)',
    price: 22,
    image: 'https://m.media-amazon.com/images/I/81PfmDNOS+L._UF1000,1000_QL80_.jpg',
    description: 'Cheerful yellow sunflowers that follow the sun, bringing positivity and joy. ₹22 per piece, ₹190 per kg.',
    category: 'sunflowers',
    origin: 'India',
    color: 'yellow',
    occasion: ['birthday', 'get-well', 'congratulations'],
    inStock: true,
    rating: 4.7,
    reviews: 203,
    sizes: ['single', 'bouquet', 'arrangement'],
    sameDay: false
  },
  {
    id: '10',
    name: 'Fragrant Tuberose (Rajnigandha)',
    price: 20,
    image: 'https://m.media-amazon.com/images/I/61aeDFrSYmL._UF1000,1000_QL80_.jpg',
    description: 'Intensely fragrant white tuberose, blooming at night with heavenly scent. ₹20 per piece, ₹180 per kg.',
    category: 'tuberose',
    origin: 'India',
    color: 'white',
    occasion: ['evening', 'fragrance', 'decoration'],
    inStock: true,
    rating: 4.8,
    reviews: 134,
    sizes: ['spike', 'bouquet', 'arrangement'],
    sameDay: false
  },
  {
    id: '11',
    name: 'White Chrysanthemums',
    price: 16,
    image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTNRQNz6EX3jRYgZErr8SlphsPfrNmfoVgpwg&s',
    description: 'Pure white chrysanthemums symbolizing loyalty and honesty. ₹16 per piece, ₹160 per kg.',
    category: 'chrysanthemums',
    origin: 'India',
    color: 'white',
    occasion: ['sympathy', 'respect', 'honor'],
    inStock: true,
    rating: 4.6,
    reviews: 156,
    sizes: ['bouquet', 'arrangement', 'single'],
    sameDay: false
  },
  {
    id: '12',
    name: 'Yellow Chrysanthemum Bunch',
    price: 17,
    image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTLiFa9AHl3xZVCaf-5U2aariVwCWJuzEwGqA&s',
    description: 'Bright yellow chrysanthemums representing joy and optimism. ₹17 per piece, ₹170 per kg.',
    category: 'chrysanthemums',
    origin: 'India',
    color: 'yellow',
    occasion: ['birthday', 'celebration', 'friendship'],
    inStock: true,
    rating: 4.7,
    reviews: 178,
    sizes: ['bunch', 'bouquet', 'arrangement'],
    sameDay: false
  },
  {
    id: '13',
    name: 'White Daisies (Sevanthi)',
    price: 14,
    image: 'https://santhionlineplants.com/wp-content/uploads/2022/07/Sevanthi-Paper-white-3.jpg',
    description: 'Simple white daisies with yellow centers, representing innocence and purity. ₹14 per piece, ₹140 per kg.',
    category: 'daisies',
    origin: 'India',
    color: 'white',
    occasion: ['simplicity', 'innocence', 'casual'],
    inStock: true,
    rating: 4.5,
    reviews: 123,
    sizes: ['bunch', 'bouquet', 'loose'],
    sameDay: false
  },
  {
    id: '14',
    name: 'Pink Bougainvillea',
    price: 13,
    image: 'https://m.media-amazon.com/images/I/512HEj+RV3L._UF1000,1000_QL80_.jpg',
    description: 'Vibrant pink bougainvillea bracts, perfect for tropical decorations. ₹13 per piece, ₹130 per kg.',
    category: 'bougainvillea',
    origin: 'India',
    color: 'pink',
    occasion: ['tropical', 'decoration', 'garden'],
    inStock: true,
    rating: 4.4,
    reviews: 87,
    sizes: ['branch', 'arrangement', 'decoration'],
    sameDay: false
  },
  {
    id: '15',
    name: 'Purple Orchids',
    price: 24,
    image: 'https://www.bbassets.com/media/uploads/p/xl/40201306_1-fresho-purple-orchids.jpg',
    description: 'Exotic purple orchids representing luxury, strength, and beauty. ₹24 per piece, ₹195 per kg.',
    category: 'orchids',
    origin: 'India',
    color: 'purple',
    occasion: ['luxury', 'exotic', 'special'],
    inStock: true,
    rating: 4.8,
    reviews: 145,
    sizes: ['plant', 'cut-flowers', 'arrangement'],
    sameDay: false
  },
  {
    id: '16',
    name: 'Red Gerbera Daisies',
    price: 19,
    image: 'https://img.freepik.com/premium-photo/red-gerbera-daisy-flower-isolated-white-background_146936-867.jpg',
    description: 'Vibrant red gerbera daisies bringing cheerfulness and energy. ₹19 per piece, ₹175 per kg.',
    category: 'gerberas',
    origin: 'India',
    color: 'red',
    occasion: ['birthday', 'celebration', 'energy'],
    inStock: true,
    rating: 4.7,
    reviews: 167,
    sizes: ['bouquet', 'arrangement', 'single'],
    sameDay: false
  },
  {
    id: '17',
    name: 'White Lilies',
    price: 23,
    image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRAqWsp6ZA_uM5xWcShBVqchnCxnizjNH-dVA&s',
    description: 'Pure white lilies symbolizing rebirth and purity. ₹23 per piece, ₹185 per kg.',
    category: 'lilies',
    origin: 'India',
    color: 'white',
    occasion: ['sympathy', 'purity', 'rebirth'],
    inStock: true,
    rating: 4.8,
    reviews: 134,
    sizes: ['bouquet', 'arrangement', 'single'],
    sameDay: false
  },
  {
    id: '18',
    name: 'Red Gladiolus',
    price: 21,
    image: 'https://plantparadise.in/cdn/shop/products/nurserylive-bulbs-gladiolus-red-bulbs-16968884977804.jpg?v=1691200230',
    description: 'Tall red gladiolus spikes representing strength and moral integrity. ₹21 per piece, ₹180 per kg.',
    category: 'gladiolus',
    origin: 'India',
    color: 'red',
    occasion: ['strength', 'honor', 'remembrance'],
    inStock: true,
    rating: 4.6,
    reviews: 98,
    sizes: ['spike', 'bunch', 'arrangement'],
    sameDay: false
  },

  // Traditional Indian Flowers and Leaves - PREVIOUS ADDITIONS
  {
    id: '41',
    name: 'Orange Crossandra',
    price: 1899,
    image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT2Eyow_rT4GprBWkiAmbma4ovpODYZn8D1CA&s',
    description: 'Vibrant orange crossandra flowers from Southern India, perfect for decorative and cultural purposes.',
    category: 'crossandra',
    origin: 'Southern India',
    color: 'orange',
    occasion: ['decoration', 'cultural', 'festival'],
    inStock: true,
    rating: 4.6,
    reviews: 89,
    sizes: ['bunch', 'garland', 'loose'],
    sameDay: true
  },
  {
    id: '42',
    name: 'Yellow Crossandra',
    price: 1799,
    image: 'https://santhionlineplants.com/wp-content/uploads/2021/06/61-jhPdHRNL._SX466_.jpg',
    description: 'Traditional yellow crossandra used for making garlands, venis, and gajras in South Indian festivals and religious ceremonies.',
    category: 'crossandra',
    origin: 'Southern India',
    color: 'yellow',
    occasion: ['religious', 'festival', 'garland-making'],
    inStock: true,
    rating: 4.7,
    reviews: 112,
    sizes: ['garland', 'veni', 'gajra'],
    sameDay: true
  },
  {
    id: '43',
    name: 'Night Flowering Jasmine (Parijatham)',
    price: 3499,
    image: 'https://nurserylive.com/cdn/shop/products/nurserylive-plants-parijat-tree-parijatak-night-flowering-jasmine-plant-16969158688908.jpg?v=1634225455',
    description: 'Sacred night-flowering jasmine with medicinal properties, highly valued in Ayurveda for its diverse therapeutic benefits.',
    category: 'jasmine',
    origin: 'India',
    color: 'white',
    occasion: ['medicinal', 'ayurveda', 'spiritual'],
    inStock: true,
    rating: 4.8,
    reviews: 156,
    sizes: ['plant', 'flowers', 'medicinal-bundle'],
    sameDay: false
  },
  {
    id: '44',
    name: 'Crown Flower',
    price: 2299,
    image: 'https://m.media-amazon.com/images/I/31K6HTz87BL._UF1000,1000_QL80_.jpg',
    description: 'Sacred crown flowers used in traditional medicine, religious practices, and ornamental gardening with natural pest control properties.',
    category: 'crown-flower',
    origin: 'India',
    color: 'white',
    occasion: ['medicinal', 'religious', 'pest-control'],
    inStock: true,
    rating: 4.5,
    reviews: 78,
    sizes: ['single', 'bunch', 'medicinal-pack'],
    sameDay: true
  },
  {
    id: '45',
    name: 'Butterfly Pea (Shankhupushpam)',
    price: 2799,
    image: 'https://m.media-amazon.com/images/I/51nQRFzv+JL._UF1000,1000_QL80_.jpg',
    description: 'Beautiful blue butterfly pea flowers known for skin hydration, weight loss support, and blood sugar regulation properties.',
    category: 'butterfly-pea',
    origin: 'Burma',
    color: 'blue',
    occasion: ['medicinal', 'wellness', 'beauty'],
    inStock: true,
    rating: 4.7,
    reviews: 134,
    sizes: ['dried', 'fresh', 'tea-blend'],
    sameDay: true
  },
  {
    id: '46',
    name: 'Magnolia Champaca',
    price: 8999,
    image: 'https://d3mbwbgtcl4x70.cloudfront.net/Screenshot_2024_12_16_103716_961c4bad54.webp',
    description: 'Exquisite magnolia champaca flowers from Southeast Asia, prized for perfumery and aromatherapy as a key ingredient in luxury perfumes.',
    category: 'magnolia',
    origin: 'Southeast Asia',
    color: 'cream',
    occasion: ['perfumery', 'aromatherapy', 'luxury'],
    inStock: true,
    rating: 4.9,
    reviews: 67,
    sizes: ['single', 'perfume-grade', 'aromatherapy-pack'],
    sameDay: false
  },
  {
    id: '47',
    name: 'Sacred Mango Leaves',
    price: 899,
    image: 'https://www.greendna.in/cdn/shop/products/mango1.jpg?v=1600280357',
    description: 'Traditional mango leaves from South and Southeast Asia, essential decorative elements for traditional ceremonies and auspicious occasions.',
    category: 'leaves',
    origin: 'South Asia',
    color: 'green',
    occasion: ['traditional', 'decoration', 'auspicious'],
    inStock: true,
    rating: 4.6,
    reviews: 203,
    sizes: ['bunch', 'garland', 'decoration-pack'],
    sameDay: true
  },
  {
    id: '48',
    name: 'Rama Tulasi (Holy Basil)',
    price: 1299,
    image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRReCm1m0kQnNGMtRIhg94ZOHzNQWSh3obv2g&s',
    description: 'Sacred Rama Tulasi from India, revered for its powerful medicinal and spiritual properties in Hindu traditions and Ayurveda.',
    category: 'tulasi',
    origin: 'India',
    color: 'green',
    occasion: ['medicinal', 'spiritual', 'religious'],
    inStock: true,
    rating: 4.9,
    reviews: 298,
    sizes: ['plant', 'leaves', 'spiritual-bundle'],
    sameDay: true
  },

  // NEW MEDICINAL AND SACRED FLOWERS/LEAVES
  {
    id: '49',
    name: 'Ashwagandha',
    price: 3299,
    image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSMJNznYRrrad9ss8C5RCx30zyIy15UbtwokQ&s',
    description: 'Powerful adaptogenic herb from India and North Africa, renowned for managing stress and anxiety naturally.',
    category: 'ashwagandha',
    origin: 'India',
    color: 'green',
    occasion: ['medicinal', 'stress-relief', 'ayurveda'],
    inStock: true,
    rating: 4.8,
    reviews: 245,
    sizes: ['dried-root', 'powder', 'medicinal-bundle'],
    sameDay: true
  },
  {
    id: '50',
    name: 'Boswellia (Frankincense)',
    price: 4599,
    image: 'https://omniactives.com/wp-content/uploads/2021/05/Boswellia_Serrata.jpg',
    description: 'Sacred Boswellia resin from trees found in India, Middle East, and North Africa, prized for its anti-inflammatory properties.',
    category: 'boswellia',
    origin: 'Middle East',
    color: 'cream',
    occasion: ['medicinal', 'spiritual', 'aromatherapy'],
    inStock: true,
    rating: 4.7,
    reviews: 189,
    sizes: ['resin', 'powder', 'incense'],
    sameDay: false
  },
  {
    id: '51',
    name: 'Brahma Kamal Leaves',
    price: 5999,
    image: 'https://cdn.shopify.com/s/files/1/0646/8327/8550/files/IMG_6927_480x480.webp?v=1717660500',
    description: 'Sacred Brahma Kamal leaves from Myanmar and Himalayan regions, used for fever, respiratory problems, digestive issues, and skin conditions.',
    category: 'brahma-kamal',
    origin: 'Myanmar',
    color: 'green',
    occasion: ['medicinal', 'respiratory-health', 'ayurveda'],
    inStock: true,
    rating: 4.9,
    reviews: 134,
    sizes: ['fresh-leaves', 'dried', 'medicinal-pack'],
    sameDay: false
  },
  {
    id: '52',
    name: 'Cumin Leaves',
    price: 1899,
    image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTVmayi0RaN6KGDBTkX8uWuqjEXAHU-PrGRlw&s',
    description: 'Aromatic cumin leaves from Eastern Mediterranean and Southwestern Asia, traditionally used for digestive issues and other ailments.',
    category: 'cumin',
    origin: 'Eastern Mediterranean',
    color: 'green',
    occasion: ['medicinal', 'digestive-health', 'culinary'],
    inStock: true,
    rating: 4.6,
    reviews: 167,
    sizes: ['fresh-leaves', 'dried', 'culinary-pack'],
    sameDay: true
  },
  {
    id: '53',
    name: 'Star Jasmine (Virajaji)',
    price: 3799,
    image: 'https://i.etsystatic.com/32153307/r/il/1d21a7/3548530804/il_1080xN.3548530804_mryj.jpg',
    description: 'Fragrant star jasmine from India and Southeast Asia, used in religious ceremonies, garlands, perfumes, and traditional medicine.',
    category: 'jasmine',
    origin: 'India',
    color: 'white',
    occasion: ['religious', 'perfumery', 'traditional-medicine'],
    inStock: true,
    rating: 4.8,
    reviews: 198,
    sizes: ['garland', 'loose-flowers', 'perfume-grade'],
    sameDay: true
  },
  {
    id: '54',
    name: 'Marugu/Maruvam (Majorana)',
    price: 2299,
    image: 'https://www.itslife.in/wp-content/gallery/gardening/gardening-majoram.jpg',
    description: 'Aromatic Origanum majorana leaves from Mediterranean region, valued for their medicinal properties and culinary uses.',
    category: 'maruvam',
    origin: 'Mediterranean',
    color: 'green',
    occasion: ['medicinal', 'culinary', 'aromatherapy'],
    inStock: true,
    rating: 4.7,
    reviews: 156,
    sizes: ['fresh-leaves', 'dried', 'medicinal-bundle'],
    sameDay: true
  },
  {
    id: '55',
    name: 'Betel Leaves (Paan)',
    price: 1599,
    image: 'https://cdn.britannica.com/02/218302-050-B19E71BA/betel-pepper-or-pan-plant-piper-betle-leaves.jpg',
    description: 'Traditional betel leaves from Southeast Asia, used for improving digestion, promoting oral hygiene, flavoring, and religious pooja.',
    category: 'betel',
    origin: 'Southeast Asia',
    color: 'green',
    occasion: ['religious', 'digestive-health', 'oral-hygiene'],
    inStock: true,
    rating: 4.6,
    reviews: 234,
    sizes: ['fresh-leaves', 'bundle', 'pooja-pack'],
    sameDay: true
  },
  {
    id: '56',
    name: 'Arabian Jasmine (Gundu Malli)',
    price: 19,
    image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQKebWTgFjLf3HbYB9aFCScTlUNxABibFCAtA&s',
    description: 'Fragrant Arabian jasmine from India and Southeast Asia, perfect for garlands, hair decoration, aromatherapy, and traditional medicine. ₹19 per piece, ₹175 per kg.',
    category: 'jasmine',
    origin: 'India',
    color: 'white',
    occasion: ['hair-decoration', 'aromatherapy', 'traditional-medicine'],
    inStock: true,
    rating: 4.8,
    reviews: 178,
    sizes: ['garland', 'loose-flowers', 'hair-decoration'],
    sameDay: false
  },
  {
    id: '57',
    name: 'Crown Leaves (Bilva)',
    price: 2799,
    image: 'https://www.iafaforallergy.com/wp-content/uploads/2023/11/Bilva-%E2%80%93-Aegle-marmelos-Corr.webp',
    description: 'Sacred Bilva leaves for Hindu worship, particularly revered for Lord Shiva, believed to originate from divine tears of Goddess Parvati.',
    category: 'bilva',
    origin: 'India',
    color: 'green',
    occasion: ['religious', 'spiritual', 'lord-shiva'],
    inStock: true,
    rating: 4.9,
    reviews: 267,
    sizes: ['fresh-leaves', 'bundle', 'worship-pack'],
    sameDay: true
  },
  {
    id: '58',
    name: 'Tanner\'s Cassia (Tangedu)',
    price: 2599,
    image: 'https://www.shutterstock.com/shutterstock/photos/2365066715/display_1500/stock-photo-tangedu-flower-is-an-important-flower-for-making-bathukamma-a-special-festival-of-telangana-2365066715.jpg',
    description: 'Traditional Cassia auriculata from Indian subcontinent, used for pain, fever, urinary disorders, rheumatism, and religious ceremonies.',
    category: 'cassia',
    origin: 'India',
    color: 'yellow',
    occasion: ['medicinal', 'festival', 'bathukamma'],
    inStock: true,
    rating: 4.7,
    reviews: 145,
    sizes: ['flowers', 'medicinal-pack', 'festival-bundle'],
    sameDay: true
  },
  {
    id: '59',
    name: 'Pinwheel Flowers (Nandivardhana)',
    price: 3399,
    image: 'https://5.imimg.com/data5/GT/GH/IQ/SELLER-92077200/nandivardhanam-tabernaemontana-divaricata.jpg',
    description: 'Sacred Tabernaemontana divaricata from South Asia, traditionally used for religious and medicinal purposes.',
    category: 'pinwheel',
    origin: 'South Asia',
    color: 'white',
    occasion: ['religious', 'medicinal', 'spiritual'],
    inStock: true,
    rating: 4.6,
    reviews: 123,
    sizes: ['flowers', 'medicinal-bundle', 'religious-pack'],
    sameDay: true
  },
  {
    id: '60',
    name: 'Crepe Jasmine (Garudavardhana)',
    price: 3599,
    image: 'https://5.imimg.com/data5/YB/SC/SJ/SELLER-92077200/garuda-vardhanam-500x500.jpg',
    description: 'Beautiful Tabernaemontana divaricata from South Asia, valued for its ornamental beauty and traditional medicinal applications.',
    category: 'crepe-jasmine',
    origin: 'India',
    color: 'white',
    occasion: ['ornamental', 'medicinal', 'traditional'],
    inStock: true,
    rating: 4.7,
    reviews: 167,
    sizes: ['flowers', 'plant', 'medicinal-pack'],
    sameDay: true
  },
  {
    id: '61',
    name: 'Jasminum Auriculatum (Chukka Malli)',
    price: 2899,
    image: 'https://i.ytimg.com/vi/XG7DMi_IWVE/hq720_2.jpg?sqp=-oaymwEYCI4CEOADSFryq4qpAwoIARUAAIhC0AEB&rs=AOn4CLBZnyJQsCw84TBfHQ5EADT7vjx7Yw',
    description: 'Traditional Indian jasmine known for its health benefits and fragrant white flowers, used in Ayurvedic medicine.',
    category: 'jasmine',
    origin: 'India',
    color: 'white',
    occasion: ['medicinal', 'health-benefits', 'ayurveda'],
    inStock: true,
    rating: 4.8,
    reviews: 189,
    sizes: ['flowers', 'medicinal-bundle', 'health-pack'],
    sameDay: true
  },
  {
    id: '62',
    name: 'Desi Rose (Naatu Gulabi)',
    price: 4299,
    image: 'https://santhionlineplants.com/wp-content/uploads/2021/06/Pinkish-Red-Rose-1-1.jpg',
    description: 'Traditional Indian country rose with natural fragrance and medicinal properties, commonly found throughout India.',
    category: 'roses',
    origin: 'India',
    color: 'pink',
    occasion: ['traditional', 'medicinal', 'natural-fragrance'],
    inStock: true,
    rating: 4.7,
    reviews: 198,
    sizes: ['single', 'bunch', 'traditional-pack'],
    sameDay: true
  },
  {
    id: '63',
    name: 'Neelakurinji',
    price: 7999,
    image: 'https://www.ekeralatourism.net/wp-content/uploads/2018/08/img6.jpg',
    description: 'Rare Neelakurinji flowers from Western Ghats, blooming once every 12 years, valued for ornamental beauty and ecosystem role.',
    category: 'neelakurinji',
    origin: 'Western Ghats',
    color: 'blue',
    occasion: ['ornamental', 'ecosystem', 'rare-bloom'],
    inStock: true,
    rating: 4.9,
    reviews: 89,
    sizes: ['rare-flowers', 'ornamental-pack', 'ecosystem-bundle'],
    sameDay: false
  },
  {
    id: '64',
    name: 'Yellow Burflower (Kadamba)',
    price: 3799,
    image: 'https://greenparadiselive.com/cdn/shop/files/Kadamba_Plant_2.png?v=1726047184&width=1920',
    description: 'Sacred Kadamba flowers from Karnataka, used for medicinal applications, ornamental purposes, and timber production.',
    category: 'kadamba',
    origin: 'Karnataka',
    color: 'yellow',
    occasion: ['medicinal', 'ornamental', 'sacred'],
    inStock: true,
    rating: 4.6,
    reviews: 156,
    sizes: ['flowers', 'medicinal-pack', 'ornamental-bundle'],
    sameDay: true
  },
  {
    id: '65',
    name: 'Night-flowering Jasmine (Parijatham)',
    price: 4199,
    image: 'https://qph.cf2.quoracdn.net/main-qimg-0131e5bc81a2860f3372380808655787-lq',
    description: 'Sacred Parijatham from India and Nepal, used in Ayurveda for treating fevers, arthritis, cough, worm infestations, and skin issues.',
    category: 'jasmine',
    origin: 'India',
    color: 'white',
    occasion: ['ayurveda', 'fever-treatment', 'skin-care'],
    inStock: true,
    rating: 4.8,
    reviews: 234,
    sizes: ['flowers', 'medicinal-bundle', 'ayurvedic-pack'],
    sameDay: true
  },
  {
    id: '66',
    name: 'Shami Flower',
    price: 2199,
    image: 'https://m.media-amazon.com/images/I/61qBwPCOSYL._UF1000,1000_QL80_.jpg',
    description: 'Sacred Shami flowers from Indian subcontinent, traditionally used for religious ceremonies and medicinal purposes.',
    category: 'shami',
    origin: 'India',
    color: 'yellow',
    occasion: ['religious', 'medicinal', 'sacred-ceremonies'],
    inStock: true,
    rating: 4.7,
    reviews: 178,
    sizes: ['flowers', 'religious-pack', 'medicinal-bundle'],
    sameDay: true
  },
  {
    id: '67',
    name: 'Cannonball Tree (Naga Malli)',
    price: 6999,
    image: 'https://www.shutterstock.com/shutterstock/photos/1448157614/display_1500/stock-photo-cannonball-tree-or-nagamalli-tree-flower-close-up-1448157614.jpg',
    description: 'Exotic Cannonball tree flowers from South American rainforests, used for religious ceremonies and traditional medicinal purposes.',
    category: 'cannonball',
    origin: 'South America',
    color: 'orange',
    occasion: ['religious', 'medicinal', 'exotic'],
    inStock: true,
    rating: 4.6,
    reviews: 123,
    sizes: ['flowers', 'religious-pack', 'medicinal-bundle'],
    sameDay: false
  },
  {
    id: '68',
    name: 'White Gerberas',
    price: 20,
    image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQNe42_jqOAgTJBZKZZ73KXY8BIGH1SVeor0Q&s',
    description: 'Pure white gerberas used as decorative garden plants or cut flowers. ₹20 per piece, ₹180 per kg.',
    category: 'gerberas',
    origin: 'South Africa',
    color: 'white',
    occasion: ['decorative', 'garden', 'arrangements'],
    inStock: true,
    rating: 4.7,
    reviews: 156,
    sizes: ['single', 'bouquet', 'arrangement'],
    sameDay: false
  },
  {
    id: '69',
    name: 'Pink Gerberas',
    price: 60,
    image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQtwswh__odjwH55mZdbhIaqcVyrJ7G3oK1cg&s',
    description: 'Beautiful pink gerberas used for decorative and gifting purposes, including bouquets and arrangements. ₹60 per piece, ₹195 per kg.',
    category: 'gerberas',
    origin: 'South Africa',
    color: 'pink',
    occasion: ['decorative', 'gifting', 'bouquets'],
    inStock: true,
    rating: 4.8,
    reviews: 189,
    sizes: ['single', 'bouquet', 'arrangement'],
    sameDay: false
  },
  {
    id: '70',
    name: 'Yellow Gerberas',
    price: 18,
    image: 'https://m.media-amazon.com/images/I/515tZCTkE-L._UF1000,1000_QL80_.jpg',
    description: 'Bright yellow gerberas used for decorative and gifting purposes, including bouquets and arrangements. ₹18 per piece, ₹170 per kg.',
    category: 'gerberas',
    origin: 'South Africa',
    color: 'yellow',
    occasion: ['decorative', 'gifting', 'arrangements'],
    inStock: true,
    rating: 4.6,
    reviews: 167,
    sizes: ['single', 'bouquet', 'arrangement'],
    sameDay: false
  },

  // NEW HIBISCUS VARIETIES AND WHITE LOTUS
  {
    id: '71',
    name: 'Light Pink Hibiscus',
    price: 15,
    image: 'https://www.saharanpurnursery.in/cdn/shop/files/hibiscuspinkdesi4.jpg?v=1718611148',
    description: 'Delicate light pink hibiscus from tropical regions including Mauritius, Madagascar, Fiji, Hawaii, and India, perfect for ornamental decoration. ₹15 per piece, ₹150 per kg.',
    category: 'hibiscus',
    origin: 'India',
    color: 'pink',
    occasion: ['ornamental', 'decoration', 'tropical'],
    inStock: true,
    rating: 4.6,
    reviews: 145,
    sizes: ['single', 'bunch', 'arrangement'],
    sameDay: false
  },
  {
    id: '72',
    name: 'White Hibiscus',
    price: 15,
    image: 'https://vgrgardens.com/wp-content/uploads/2022/10/White_Hibiscus_5821-scaled-e1667380053680-1.jpeg',
    description: 'Pure white hibiscus from Hawaiian Islands, used for ornamental decoration, traditional medicine, and as a food ingredient. ₹15 per piece, ₹150 per kg.',
    category: 'hibiscus',
    origin: 'Hawaiian Islands',
    color: 'white',
    occasion: ['ornamental', 'medicinal', 'culinary'],
    inStock: true,
    rating: 4.7,
    reviews: 167,
    sizes: ['single', 'bunch', 'medicinal-pack'],
    sameDay: false
  },
  {
    id: '73',
    name: 'Sacred White Lotus',
    price: 25,
    image: 'https://m.media-amazon.com/images/I/51D5p2+iEIL._UF350,350_QL80_.jpg',
    description: 'Sacred white lotus from Africa and Asia, representing purity, enlightenment, and spiritual awakening in Buddhist and Hindu traditions. ₹25 per piece, ₹200 per kg.',
    category: 'lotus',
    origin: 'Asia',
    color: 'white',
    occasion: ['spiritual', 'enlightenment', 'meditation'],
    inStock: true,
    rating: 4.9,
    reviews: 234,
    sizes: ['single', 'pair', 'spiritual-arrangement'],
    sameDay: false
  },
  {
    id: '74',
    name: 'Dark Pink Hibiscus',
    price: 15,
    image: 'https://homelyfeelgardens.com/cdn/shop/files/FullSizeRender_37f649ef-91fc-48c6-ae4c-c0f24acf3f3e.jpg?v=1703735586',
    description: 'Vibrant dark pink hibiscus from Asia and Pacific Islands, used for decorative and medicinal purposes with striking color. ₹15 per piece, ₹150 per kg.',
    category: 'hibiscus',
    origin: 'Asia',
    color: 'pink',
    occasion: ['decorative', 'medicinal', 'vibrant'],
    inStock: true,
    rating: 4.6,
    reviews: 189,
    sizes: ['single', 'bunch', 'decorative-pack'],
    sameDay: false
  },
  {
    id: '75',
    name: 'Orange Hibiscus',
    price: 15,
    image: 'https://m.media-amazon.com/images/I/41QfS8VkQVL._UF1000,1000_QL80_.jpg',
    description: 'Bright orange hibiscus from tropical Asia, perfect for ornamental purposes in gardens, adding vibrant color and attracting pollinators. ₹15 per piece, ₹150 per kg.',
    category: 'hibiscus',
    origin: 'Tropical Asia',
    color: 'orange',
    occasion: ['ornamental', 'garden', 'pollinator-friendly'],
    inStock: true,
    rating: 4.7,
    reviews: 156,
    sizes: ['single', 'bunch', 'garden-pack'],
    sameDay: false
  },
  {
    id: '76',
    name: 'Hibiscus Rosa-Sinensis (Mudda Mandaram)',
    price: 15,
    image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQmygX-eh0hne3jYfjQEULDbVAx4UrVoUDFmg&s',
    description: 'Traditional Hibiscus rosa-sinensis from tropical Asia, used for medicinal, culinary, decorative applications, and religious pooja ceremonies. ₹15 per piece, ₹150 per kg.',
    category: 'hibiscus',
    origin: 'India',
    color: 'red',
    occasion: ['medicinal', 'culinary', 'pooja'],
    inStock: true,
    rating: 4.8,
    reviews: 198,
    sizes: ['single', 'bunch', 'pooja-pack'],
    sameDay: false
  },

  // NEW CHRYSANTHEMUM VARIETIES
  {
    id: '77',
    name: 'Red Chrysanthemums',
    price: 18,
    image: 'https://cdn.britannica.com/05/12905-004-10411038/Chrysanthemum.jpg',
    description: 'Vibrant red chrysanthemums from East Asia, symbolizing love and deep passion with their rich, velvety petals. ₹18 per piece, ₹175 per kg.',
    category: 'chrysanthemums',
    origin: 'East Asia',
    color: 'red',
    occasion: ['love', 'passion', 'romantic'],
    inStock: true,
    rating: 4.8,
    reviews: 189,
    sizes: ['bouquet', 'arrangement', 'single'],
    sameDay: false
  },
  {
    id: '78',
    name: 'Pink Chrysanthemums',
    price: 17,
    image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ2li0S46ZgYwsmks9bIDPSP4isQ5Y1WCCSRg&s',
    description: 'Elegant pink chrysanthemums from East Asia, primarily China, representing grace, beauty, and gentle affection. ₹17 per piece, ₹170 per kg.',
    category: 'chrysanthemums',
    origin: 'East Asia',
    color: 'pink',
    occasion: ['grace', 'beauty', 'affection'],
    inStock: true,
    rating: 4.7,
    reviews: 167,
    sizes: ['bouquet', 'arrangement', 'bunch'],
    sameDay: false
  },
  {
    id: '79',
    name: 'Multi-colored Chrysanthemums',
    price: 19,
    image: 'https://i.ytimg.com/vi/73RSUSqAEL8/sddefault.jpg',
    description: 'Stunning multi-colored chrysanthemums perfect for floral arrangements, adding vibrant color and texture to bouquets and displays. ₹19 per piece, ₹180 per kg.',
    category: 'chrysanthemums',
    origin: 'East Asia',
    color: 'mixed',
    occasion: ['arrangements', 'vibrant', 'decorative'],
    inStock: true,
    rating: 4.8,
    reviews: 234,
    sizes: ['mixed-bouquet', 'arrangement', 'display-pack'],
    sameDay: false
  },

  // Dutch/Netherlands Flowers
  {
    id: '19',
    name: 'Classic Red Tulips',
    price: 5799,
    image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSFGieRGt2bNri_Le3acfKirq3zcwjvKCVcUw&s',
    description: 'Iconic Dutch red tulips, symbols of perfect love and elegance.',
    category: 'tulips',
    origin: 'Netherlands',
    color: 'red',
    occasion: ['spring', 'love', 'classic'],
    inStock: true,
    rating: 4.9,
    reviews: 234,
    sizes: ['dozen', 'bouquet', 'arrangement'],
    sameDay: false
  },
  {
    id: '20',
    name: 'Yellow Dutch Tulips',
    price: 5299,
    image: 'https://media.gettyimages.com/id/1770145751/photo/the-last-sunbeams-enjoying-the-beauty-of-yellow-tulips-fields-and-a-traditional-dutch.jpg?s=612x612&w=gi&k=20&c=mCU0SofYYsPl4A1GK4k6pRqj1RsBB0kktO7jxIk3il8=',
    description: 'Bright yellow tulips bringing sunshine and cheerfulness from Holland.',
    category: 'tulips',
    origin: 'Netherlands',
    color: 'yellow',
    occasion: ['spring', 'cheerfulness', 'friendship'],
    inStock: true,
    rating: 4.8,
    reviews: 189,
    sizes: ['dozen', 'bouquet', 'mixed'],
    sameDay: false
  },
  {
    id: '21',
    name: 'Pink Tulip Elegance',
    price: 5499,
    image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ2rKS3Q0eReNlwqbqgsmDQkaq0mCdHpBgUrw&s',
    description: 'Soft pink tulips representing affection and caring.',
    category: 'tulips',
    origin: 'Netherlands',
    color: 'pink',
    occasion: ['affection', 'caring', 'spring'],
    inStock: true,
    rating: 4.8,
    reviews: 156,
    sizes: ['dozen', 'bouquet', 'arrangement'],
    sameDay: false
  },
  {
    id: '22',
    name: 'Purple Tulip Royalty',
    price: 6099,
    image: 'https://media.istockphoto.com/id/1372188481/photo/spring-sunny-day-purple-tulips.jpg?s=612x612&w=0&k=20&c=HcERKBH3Be0SlYwiNrojc8P3QiMdChKZB3T0u6bW7E0=',
    description: 'Regal purple tulips symbolizing royalty and rebirth.',
    category: 'tulips',
    origin: 'Netherlands',
    color: 'purple',
    occasion: ['royalty', 'elegance', 'rebirth'],
    inStock: true,
    rating: 4.9,
    reviews: 167,
    sizes: ['dozen', 'premium-bouquet', 'arrangement'],
    sameDay: false
  },
  {
    id: '23',
    name: 'Blue Hyacinths',
    price: 3799,
    image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSHjczN0ef4qiJslW0Om-L6VRqb5YsZXkJaIQ&s',
    description: 'Fragrant blue hyacinths with their distinctive sweet scent.',
    category: 'hyacinths',
    origin: 'Netherlands',
    color: 'blue',
    occasion: ['fragrance', 'spring', 'constancy'],
    inStock: true,
    rating: 4.7,
    reviews: 123,
    sizes: ['bulb-arrangement', 'cut-flowers', 'potted'],
    sameDay: false
  },
  {
    id: '24',
    name: 'Pink Hyacinth Clusters',
    price: 3599,
    image: 'https://img.pikbest.com/png-images/20250317/vibrant-pink-hyacinth-floral-cluster_11605436.png!w700wp',
    description: 'Sweet-scented pink hyacinths perfect for spring celebrations.',
    category: 'hyacinths',
    origin: 'Netherlands',
    color: 'pink',
    occasion: ['spring', 'playfulness', 'sport'],
    inStock: true,
    rating: 4.6,
    reviews: 98,
    sizes: ['cluster', 'arrangement', 'potted'],
    sameDay: false
  },
  {
    id: '25',
    name: 'Yellow Daffodils',
    price: 3299,
    image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQY-hevpCfWiLpmZjdGaVOKQ3GElqB8_frwYg&s',
    description: 'Cheerful yellow daffodils heralding the arrival of spring.',
    category: 'daffodils',
    origin: 'Netherlands',
    color: 'yellow',
    occasion: ['spring', 'new-beginnings', 'hope'],
    inStock: true,
    rating: 4.7,
    reviews: 145,
    sizes: ['bunch', 'bouquet', 'naturalized'],
    sameDay: false
  },
  {
    id: '26',
    name: 'White Daffodil Purity',
    price: 3499,
    image: 'https://image.gardeningbazar.com/fit-in/600x600/a4d45bdd-695a-4de7-a4bf-50b02a5e963f.webp',
    description: 'Pure white daffodils with orange centers, symbols of rebirth.',
    category: 'daffodils',
    origin: 'Netherlands',
    color: 'white',
    occasion: ['rebirth', 'new-beginnings', 'purity'],
    inStock: true,
    rating: 4.8,
    reviews: 134,
    sizes: ['bunch', 'arrangement', 'mixed'],
    sameDay: false
  },
  {
    id: '27',
    name: 'Purple Crocuses',
    price: 2199,
    image: 'https://m.media-amazon.com/images/I/81+VFQI+tuL.jpg',
    description: 'Delicate purple crocuses, first flowers of spring.',
    category: 'crocuses',
    origin: 'Netherlands',
    color: 'purple',
    occasion: ['early-spring', 'delicate', 'first-love'],
    inStock: true,
    rating: 4.5,
    reviews: 87,
    sizes: ['cluster', 'naturalized', 'small-bouquet'],
    sameDay: false
  },
  {
    id: '28',
    name: 'Red Amaryllis',
    price: 7199,
    image: 'https://seedsnpots.com/wp-content/uploads/2024/04/amaryllis-red-lion.jpg',
    description: 'Stunning red amaryllis with large, trumpet-shaped blooms.',
    category: 'amaryllis',
    origin: 'Netherlands',
    color: 'red',
    occasion: ['dramatic', 'pride', 'determination'],
    inStock: true,
    rating: 4.8,
    reviews: 112,
    sizes: ['single-stem', 'potted', 'arrangement'],
    sameDay: false
  },
  {
    id: '29',
    name: 'Dutch Gerbera Mix',
    price: 4699,
    image: 'https://m.media-amazon.com/images/I/51eW0rIBjXS.jpg',
    description: 'Colorful mix of Dutch gerberas in vibrant hues.',
    category: 'gerberas',
    origin: 'Netherlands',
    color: 'mixed',
    occasion: ['cheerfulness', 'beauty', 'innocence'],
    inStock: true,
    rating: 4.7,
    reviews: 178,
    sizes: ['mixed-bouquet', 'arrangement', 'single-color'],
    sameDay: false
  },
  {
    id: '30',
    name: 'White Freesias',
    price: 4099,
    image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQRtvb8ZMa4fyvg0dBAFjzkbPjkWeWGTVipOA&s',
    description: 'Fragrant white freesias with their sweet, citrusy scent.',
    category: 'freesias',
    origin: 'Netherlands',
    color: 'white',
    occasion: ['innocence', 'friendship', 'fragrance'],
    inStock: true,
    rating: 4.6,
    reviews: 134,
    sizes: ['bunch', 'bouquet', 'mixed'],
    sameDay: false
  },
  {
    id: '31',
    name: 'Blue Irises',
    price: 4399,
    image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT2uJM_OGVr26ZvT-tBc6NErZqXMKQs0PtzeA&s',
    description: 'Luxurious pink peonies with their full, ruffled blooms.',
    category: 'peonies',
    origin: 'Netherlands',
    color: 'pink',
    occasion: ['honor', 'wealth', 'romance'],
    inStock: true,
    rating: 4.9,
    reviews: 89,
    sizes: ['bouquet', 'arrangement', 'premium'],
    sameDay: false
  },
  {
    id: '33',
    name: 'Pink Ranunculus',
    price: 5799,
    image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTYLvgtWI8A-0KCOwucXld8tL6KtZ_5TbOfNw&s',
    description: 'Delicate pink ranunculus with layers of papery petals.',
    category: 'ranunculus',
    origin: 'Netherlands',
    color: 'pink',
    occasion: ['charm', 'attractiveness', 'radiance'],
    inStock: true,
    rating: 4.7,
    reviews: 156,
    sizes: ['bouquet', 'arrangement', 'mixed'],
    sameDay: false
  },
  {
    id: '34',
    name: 'White Calla Lilies',
    price: 6599,
    image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRprWTX10rJmeHp7bcCMNQqOqljz4kjAtuGDg&s',
    description: 'Elegant white calla lilies with their distinctive trumpet shape.',
    category: 'calla-lilies',
    origin: 'Netherlands',
    color: 'white',
    occasion: ['magnificence', 'beauty', 'rebirth'],
    inStock: true,
    rating: 4.8,
    reviews: 167,
    sizes: ['single-stem', 'bouquet', 'arrangement'],
    sameDay: false
  },
  {
    id: '35',
    name: 'Blue Delphiniums',
    price: 7799,
    image: 'https://assets.americanmeadows.com/media/catalog/product/d/e/delphinium-guardian-blue.jpg?quality=85&fit=bounds&height=&width=3840&auto=webp&format=pjpg',
    description: 'Tall blue delphinium spikes creating dramatic vertical displays.',
    category: 'delphiniums',
    origin: 'Netherlands',
    color: 'blue',
    occasion: ['big-hearted', 'fun', 'lightness'],
    inStock: true,
    rating: 4.6,
    reviews: 123,
    sizes: ['tall-spike', 'arrangement', 'garden-style'],
    sameDay: false
  },

  // International Premium Flowers
  {
    id: '36',
    name: 'Ecuadorian Premium Roses',
    price: 12199,
    image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRxZzaP7zuLh6vHlytCsOhkNSxXZYV0zd2ptIKf8TNiPU_D-c2kh1UDI80aGFGX_jCXI0M&usqp=CAU',
    description: 'High-altitude Ecuadorian roses with large blooms and vibrant colors.',
    category: 'roses',
    origin: 'Ecuador',
    color: 'red',
    occasion: ['luxury', 'premium', 'special-occasions'],
    inStock: true,
    rating: 4.9,
    reviews: 298,
    sizes: ['premium-dozen', 'luxury-bouquet', 'single-premium'],
    sameDay: false
  },
  {
    id: '37',
    name: 'Colombian Carnations',
    price: 3599,
    image: 'https://i0.wp.com/floristsreview.com/wp-content/uploads/2023/03/Untitled-2-3.jpg?resize=900%2C640&ssl=1',
    description: 'Vibrant Colombian carnations known for their longevity and color.',
    category: 'carnations',
    origin: 'Colombia',
    color: 'pink',
    occasion: ['love', 'fascination', 'distinction'],
    inStock: true,
    rating: 4.7,
    reviews: 187,
    sizes: ['bunch', 'bouquet', 'mixed'],
    sameDay: false
  },
  {
    id: '38',
    name: 'Kenyan Roses',
    price: 8099,
    image: 'https://btfgroup.com/wp-content/uploads/2018/08/Kenya_Rose.jpg',
    description: 'Sustainably grown Kenyan roses with exceptional quality.',
    category: 'roses',
    origin: 'Kenya',
    color: 'pink',
    occasion: ['sustainable', 'eco-friendly', 'premium'],
    inStock: true,
    rating: 4.8,
    reviews: 234,
    sizes: ['dozen', 'bouquet', 'eco-arrangement'],
    sameDay: false
  },
  {
    id: '39',
    name: 'Australian Proteas',
    price: 9699,
    image: 'https://cdn.shopify.com/s/files/1/0093/6974/7518/files/protea-g2864c346d_1920_600x600.jpg?v=1657856539',
    description: 'Exotic Australian proteas with unique, architectural forms.',
    category: 'proteas',
    origin: 'Australia',
    color: 'mixed',
    occasion: ['exotic', 'unique', 'artistic'],
    inStock: true,
    rating: 4.6,
    reviews: 145,
    sizes: ['single', 'arrangement', 'artistic'],
    sameDay: false
  },
  {
    id: '40',
    name: 'French Lavender',
    price: 3299,
    image: 'https://appalachianbotanical.com/cdn/shop/articles/mario-mendez-kkhww8996mg-unsplashB.jpg?v=1619030420',
    description: 'Aromatic French lavender with its distinctive fragrance.',
    category: 'lavender',
    origin: 'France',
    color: 'purple',
    occasion: ['relaxation', 'fragrance', 'provence'],
    inStock: true,
    rating: 4.7,
    reviews: 167,
    sizes: ['bunch', 'dried', 'fresh'],
    sameDay: false
  },

  // NEW YELLOW ROSE
  {
    id: '80',
    name: 'Yellow Rose Friendship',
    price: 172,
    image: 'https://floweraura-blog-img.s3.ap-south-1.amazonaws.com/flower-gifts-blog/origin-of-yellow-roses.jpg',
    description: 'Beautiful yellow roses from Afghanistan and Southeast Asia, perfect for expressing friendship, joy, and happiness. ₹172 per piece, ₹182 per kg.',
    category: 'roses',
    origin: 'Afghanistan',
    color: 'yellow',
    occasion: ['friendship', 'joy', 'happiness'],
    inStock: true,
    rating: 4.8,
    reviews: 198,
    sizes: ['single', 'dozen', 'bouquet'],
    sameDay: true
  },

  // NEW YELLOW HIBISCUS
  {
    id: '81',
    name: 'Yellow Hibiscus Hawaiian',
    price: 15,
    image: 'https://m.media-amazon.com/images/I/61GYwx1-8QL._UF1000,1000_QL80_.jpg',
    description: 'Tropical yellow hibiscus from Hawaiian Islands, used for adding beauty to gardens, creating herbal teas, providing natural dyes, and potentially offering some medicinal benefits. ₹15 per piece, ₹150 per kg.',
    category: 'hibiscus',
    origin: 'Hawaiian Islands',
    color: 'yellow',
    occasion: ['garden', 'herbal-tea', 'natural-dyes'],
    inStock: true,
    rating: 4.7,
    reviews: 156,
    sizes: ['single', 'bunch', 'garden-pack'],
    sameDay: true
  },

  // NEW BLUE LOTUS
  {
    id: '82',
    name: 'Sacred Blue Lotus',
    price: 25,
    image: 'https://static.vecteezy.com/system/resources/previews/049/316/573/non_2x/lotus-flower-blue-photo.jpg',
    description: 'Sacred blue lotus from North and Central Africa, specifically around the Nile River, used in traditional medicine for thousands of years as a natural aphrodisiac, sleep aid, and anxiety reliever. ₹25 per piece, ₹200 per kg.',
    category: 'lotus',
    origin: 'North Africa',
    color: 'blue',
    occasion: ['traditional-medicine', 'sleep-aid', 'anxiety-relief'],
    inStock: true,
    rating: 4.9,
    reviews: 89,
    sizes: ['single', 'medicinal-pack', 'therapeutic-bundle'],
    sameDay: false
  },

  // NEW PINK LOTUS
  {
    id: '83',
    name: 'Pink Lotus Sacred',
    price: 25,
    image: 'https://www.dbrexportsindia.com/cdn/shop/products/PinkLotusOil.jpg?v=1661935883',
    description: 'Sacred pink lotus from India, China, and Japan, used for spiritual practices, traditional medicine, and as an ornamental plant. ₹25 per piece, ₹200 per kg.',
    category: 'lotus',
    origin: 'India',
    color: 'pink',
    occasion: ['spiritual', 'traditional-medicine', 'ornamental'],
    inStock: true,
    rating: 4.9,
    reviews: 167,
    sizes: ['single', 'spiritual-pack', 'medicinal-bundle'],
    sameDay: false
  },

  // NEW RED KRISHNA BANTHI
  {
    id: '84',
    name: 'Red Krishna Banthi (Karapu Banthi)',
    price: 30,
    image: 'https://i.ytimg.com/vi/-EQgVZ9FrZ4/mqdefault.jpg',
    description: 'Sacred red Krishna Banthi from Mexico and Central America, used for religious ceremonies and traditional worship. ₹30 per kg.',
    category: 'krishna-banthi',
    origin: 'Mexico',
    color: 'red',
    occasion: ['religious', 'spiritual', 'ceremonies'],
    inStock: true,
    rating: 4.8,
    reviews: 234,
    sizes: ['per-kg', 'bulk', 'religious-pack'],
    sameDay: true
  },

  // NEW YELLOW KRISHNA BANTHI
  {
    id: '85',
    name: 'Yellow Krishna Banthi',
    price: 30,
    image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRlYgYUDoANAo-wNyO_Muak3aqhH3_UWWSS1A&s',
    description: 'Sacred yellow Krishna Banthi from South India, used for religious pooja rituals and traditional ceremonies. ₹30 per kg.',
    category: 'krishna-banthi',
    origin: 'Southern India',
    color: 'yellow',
    occasion: ['religious', 'pooja', 'ceremonies'],
    inStock: true,
    rating: 4.9,
    reviews: 298,
    sizes: ['per-kg', 'bulk', 'pooja-pack'],
    sameDay: true
  },

  // NEW PINK HYDRANGEAS
  {
    id: '86',
    name: 'Pink Hydrangeas Japanese',
    price: 22,
    image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQNyQx1cYXgXPX8lCThmTDAT43PF4nDP4HkSw&s',
    description: 'Beautiful pink hydrangeas from Japan, used for aesthetic appeal in gardens, floral arrangements, and as decorative elements. ₹22 per piece, ₹185 per kg.',
    category: 'hydrangeas',
    origin: 'Japan',
    color: 'pink',
    occasion: ['garden', 'arrangements', 'decorative'],
    inStock: true,
    rating: 4.7,
    reviews: 178,
    sizes: ['bunch', 'arrangement', 'garden-pack'],
    sameDay: true
  },

  // NEW BLUE HYDRANGEAS
  {
    id: '87',
    name: 'Blue Hydrangeas',
    price: 23,
    image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSpjaK_Xq37Gc8AU4bfjp70BK2ru8fp1p-ZEQ&s',
    description: 'Stunning blue hydrangeas from Japan and certain parts of North America, used as ornamental plants for landscaping and cut flower arrangements. ₹23 per piece, ₹190 per kg.',
    category: 'hydrangeas',
    origin: 'Japan',
    color: 'blue',
    occasion: ['ornamental', 'landscaping', 'arrangements'],
    inStock: true,
    rating: 4.8,
    reviews: 156,
    sizes: ['bunch', 'arrangement', 'landscaping-pack'],
    sameDay: true
  },

  // NEW ORANGE TULIPS
  {
    id: '88',
    name: 'Orange Tulips Energy',
    price: 24,
    image: 'https://www.juneflowers.com/wp-content/uploads/2022/08/Orange-Tulips.jpg',
    description: 'Vibrant orange tulips from Central Asia, used to convey enthusiasm, energy, and a zest for life. ₹24 per piece, ₹195 per kg.',
    category: 'tulips',
    origin: 'Central Asia',
    color: 'orange',
    occasion: ['enthusiasm', 'energy', 'zest-for-life'],
    inStock: true,
    rating: 4.7,
    reviews: 189,
    sizes: ['dozen', 'bouquet', 'arrangement'],
    sameDay: false
  },

  // NEW WHITE TULIPS
  {
    id: '89',
    name: 'White Tulips Purity',
    price: 23,
    image: 'https://images.prismic.io/floraqueen-blog/ZtnY0rzzk9ZrXDq2_4112431.jpg?w=1000&h=600&fit=crop&auto=format,compress',
    description: 'Pure white tulips from Central Asia, used to symbolize purity, innocence, forgiveness, and new beginnings. ₹23 per piece, ₹190 per kg.',
    category: 'tulips',
    origin: 'Central Asia',
    color: 'white',
    occasion: ['purity', 'innocence', 'forgiveness', 'new-beginnings'],
    inStock: true,
    rating: 4.8,
    reviews: 167,
    sizes: ['dozen', 'bouquet', 'arrangement'],
    sameDay: false
  },

  // NEW BLACK TULIPS
  {
    id: '90',
    name: 'Black Tulips Elegance',
    price: 25,
    image: 'https://m.media-amazon.com/images/I/51nXpTk8bFL._UF1000,1000_QL80_.jpg',
    description: 'Dramatic black tulips from Central Asia, used for aesthetic and practical purposes, adding elegance and sophistication. ₹25 per piece, ₹200 per kg.',
    category: 'tulips',
    origin: 'Central Asia',
    color: 'black',
    occasion: ['elegance', 'dramatic', 'aesthetic'],
    inStock: true,
    rating: 4.9,
    reviews: 123,
    sizes: ['dozen', 'premium-bouquet', 'arrangement'],
    sameDay: false
  },

  // NEW BANANA LEAVES
  {
    id: '91',
    name: 'Fresh Banana Leaves Kerala',
    price: 50,
    image: 'https://images.indianexpress.com/2024/06/banana-leaf.jpg',
    description: 'Fresh banana leaves from Kerala, used as natural wrapping, cooking surface, and serving dish, offering both practical and culinary benefits. ₹50 per kg.',
    category: 'leaves',
    origin: 'Kerala',
    color: 'green',
    occasion: ['culinary', 'wrapping', 'serving'],
    inStock: true,
    rating: 4.6,
    reviews: 345,
    sizes: ['per-leaf', 'per-kg', 'bulk-pack'],
    sameDay: true
  },

  // NEW YELLOW OLEANDER
  {
    id: '92',
    name: 'Yellow Oleander Medicinal',
    price: 75,
    image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTheIyWUAZ7zIJa7mJ6J-OtXYfKzBEP5EppQw&s',
    description: 'Yellow oleander from Mexico and Central America, used to treat hemorrhoids, ulcers, skin conditions, herpes, and ringworm infections, and used in Hindu pooja rituals. ₹75 per kg.',
    category: 'oleander',
    origin: 'Mexico',
    color: 'yellow',
    occasion: ['medicinal', 'pooja', 'traditional-medicine'],
    inStock: true,
    rating: 4.5,
    reviews: 167,
    sizes: ['per-kg', 'medicinal-pack', 'pooja-bundle'],
    sameDay: true
  },

  // NEW PINK OLEANDER
  {
    id: '93',
    name: 'Pink Oleander Mediterranean',
    price: 70,
    image: 'https://lalitenterprise.com/cdn/shop/files/Nerium_Oleander_Double_Petal_Plant_6.webp?v=1744196230',
    description: 'Pink oleander from Mediterranean region, North Africa, and parts of Asia, widely used as ornamental plants and known for attracting butterflies and bees, also used in Hindu pooja. ₹70 per kg.',
    category: 'oleander',
    origin: 'Mediterranean',
    color: 'pink',
    occasion: ['ornamental', 'pooja', 'decorative'],
    inStock: true,
    rating: 4.6,
    reviews: 189,
    sizes: ['per-kg', 'ornamental-pack', 'pooja-bundle'],
    sameDay: true
  },

  // NEW WHITE OLEANDER
  {
    id: '94',
    name: 'White Oleander Southwest Asian',
    price: 80,
    image: 'https://www.jiomart.com/images/product/original/rvsmd19yhj/online-plant-bazar-white-oleander-flower-plant-pack-of-1-product-images-orvsmd19yhj-p600668893-0-202304182029.jpg?im=Resize=(420,420)',
    description: 'White oleander from Southwest Asia, used for treatment of diverse ailments such as heart failure, asthma, corns, cancer, diabetes, and epilepsy, and used in Hindu pooja. ₹80 per kg.',
    category: 'oleander',
    origin: 'Southwest Asia',
    color: 'white',
    occasion: ['medicinal', 'pooja', 'traditional-treatment'],
    inStock: true,
    rating: 4.7,
    reviews: 234,
    sizes: ['per-kg', 'medicinal-pack', 'pooja-bundle'],
    sameDay: true
  }
];